// Copyright (c) Microsoft Corporation.// Licensed under the MIT license.

namespace Microsoft.SCIM
{
    // Members are numerically ordered.
    internal static class ServiceNotificationIdentifiers
    {
        public const long BULK_REQUEST_2_CONTROLLER_POST_ARGUMENT_EXCEPTION = 1;
        public const long BULK_REQUEST_2_CONTROLLER_POST_EXCEPTION = 2;
        public const long BULK_REQUEST_2_CONTROLLER_POST_NOT_IMPLEMENTED_EXCEPTION = 3;
        public const long BULK_REQUEST_2_CONTROLLER_POST_NOT_SUPPORTED_EXCEPTION = 4;

        public const long CONTROLLER_TEMPLATE_DELETE_ARGUMENT_EXCEPTION = 5;
        public const long CONTROLLER_TEMPLATE_DELETE_EXCEPTION = 6;
        public const long CONTROLLER_TEMPLATE_DELETE_NOT_IMPLEMENTED_EXCEPTION = 7;
        public const long CONTROLLER_TEMPLATE_DELETE_NOT_SUPPORTED_EXCEPTION = 8;

        public const long CONTROLLER_TEMPLATE_GET_ARGUMENT_EXCEPTION = 9;
        public const long CONTROLLER_TEMPLATE_GET_EXCEPTION = 10;
        public const long CONTROLLER_TEMPLATE_GET_NOT_IMPLEMENTED_EXCEPTION = 11;
        public const long CONTROLLER_TEMPLATE_GET_NOT_SUPPORTED_EXCEPTION = 12;

        public const long CONTROLLER_TEMPLATE_PATCH_ARGUMENT_EXCEPTION = 13;
        public const long CONTROLLER_TEMPLATE_PATCH_EXCEPTION = 14;
        public const long CONTROLLER_TEMPLATE_PATCH_NOT_IMPLEMENTED_EXCEPTION = 15;
        public const long CONTROLLER_TEMPLATE_PATCH_NOT_SUPPORTED_EXCEPTION = 16;

        public const long CONTROLLER_TEMPLATE_POST_ARGUMENT_EXCEPTION = 17;
        public const long CONTROLLER_TEMPLATE_POST_EXCEPTION = 18;
        public const long CONTROLLER_TEMPLATE_POST_NOT_IMPLEMENTED_EXCEPTION = 19;
        public const long CONTROLLER_TEMPLATE_POST_NOT_SUPPORTED_EXCEPTION = 20;

        public const long CONTROLLER_TEMPLATE_PUT_ARGUMENT_EXCEPTION = 21;
        public const long CONTROLLER_TEMPLATE_PUT_EXCEPTION = 22;
        public const long CONTROLLER_TEMPLATE_PUT_NOT_IMPLEMENTED_EXCEPTION = 23;
        public const long CONTROLLER_TEMPLATE_PUT_NOT_SUPPORTED_EXCEPTION = 24;

        public const long CONTROLLER_TEMPLATE_QUERY_ARGUMENT_EXCEPTION = 25;
        public const long CONTROLLER_TEMPLATE_QUERY_NOT_IMPLEMENTED_EXCEPTION = 26;
        public const long CONTROLLER_TEMPLATE_QUERY_NOT_SUPPORTED_EXCEPTION = 27;
        public const long CONTROLLER_TEMPLATE_QUERY_EXCEPTION = 28;

        public const long MONITORING_MIDDLEWARE_INVOCATION_EXCEPTION = 29;
        public const long MONITORING_MIDDLEWARE_RECEPTION = 30;
        public const long MONITORING_MIDDLEWARE_REQUEST_PROCESSED = 31;

        public const long RESOURCE_TYPES_CONTROLLER_GET_ARGUMENT_EXCEPTION = 32;
        public const long RESOURCE_TYPES_CONTROLLER_GET_EXCEPTION = 33;
        public const long RESOURCE_TYPES_CONTROLLER_GET_NOT_IMPLEMENTED_EXCEPTION = 34;
        public const long RESOURCE_TYPES_CONTROLLER_GET_NOT_SUPPORTED_EXCEPTION = 35;

        public const long SCHEMATIZED_MEDIA_TYPE_FORMATTER_READ_FROM_STREAM = 36;
        public const long SCHEMATIZED_MEDIA_TYPE_FORMATTER_WROTE_TO_STREAM = 37;

        public const long SCHEMAS_CONTROLLER_GET_ARGUMENT_EXCEPTION = 38;
        public const long SCHEMAS_CONTROLLER_GET_EXCEPTION = 39;
        public const long SCHEMAS_CONTROLLER_GET_NOT_IMPLEMENTED_EXCEPTION = 40;
        public const long SCHEMAS_CONTROLLER_GET_NOT_SUPPORTED_EXCEPTION = 41;

        public const long SERVICE_PROVIDER_CONFIGURATION_CONTROLLER_GET_ARGUMENT_EXCEPTION = 42;
        public const long SERVICE_PROVIDER_CONFIGURATION_CONTROLLER_GET_EXCEPTION = 43;
        public const long SERVICE_PROVIDER_CONFIGURATION_CONTROLLER_GET_NOT_IMPLEMENTED_EXCEPTION = 44;
        public const long SERVICE_PROVIDER_CONFIGURATION_CONTROLLER_GET_NOT_SUPPORTED_EXCEPTION = 45;

        public const long EVENTS_CONTROLLER_POST_ARGUMENT_EXCEPTION = 46;
        public const long EVENTS_CONTROLLER_POST_EXCEPTION = 47;
        public const long EVENTS_CONTROLLER_POST_NOT_IMPLEMENTED_EXCEPTION = 48;
        public const long EVENTS_CONTROLLER_POST_NOT_SUPPORTED_EXCEPTION = 49;
    }
}
